name: Backend CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }
      - run: dotnet --info
      - run: dotnet restore server/src/CreativeCalendar.WebApi/CreativeCalendar.WebApi.csproj
      - run: dotnet build server/src/CreativeCalendar.WebApi/CreativeCalendar.WebApi.csproj -c Release --no-restore
      - run: dotnet test server -c Release --no-build || true
