name: Frontend CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm i -g pnpm@9
      - run: pnpm i
      - run: pnpm -r lint
      - run: pnpm -r test
      - run: pnpm -r build
